apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
      - name: auth-container
        image: auth:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
